### PR TITLE
Release 1.2.0

### LINKED ISSUE #200: Release new version with fixed Ember 3.9 deprecations
It looks like https://github.com/dollarshaveclub/ember-router-scroll/pull/191 fixes Ember 3.9 deprecations and was merged quite a while ago. When can we expect a new release? We're upgrading and trying to get rid of all our deprecation warnings.

### PR DESCRIPTION
**Pull request by snewcomer**
close #200 #193

### CODE REVIEW

**Comment by pichfl** [comment]
How would one fix the deprecation introduced in this release? I feel like I'm missing a step here.

**Comment by williamweckl** [comment]
@pichfl the fixes has already being made. This PR only releases it.

@snewcomer any expectations to release that?

**Comment by pichfl** [comment]
Hence why I'm asking. Installing this release will result in a deprecation warnings without a clear path on how to fix them. The text inside the warning is not helpful for consumers of the add-on. 

If I'm wrong, please point me and other people running into the same deprecation into the right direction.

**Comment by willviles** [comment]
@pichfl is right... the following deprecation warning is confusing. Help appreciated!

`DEPRECATION: If you are overriding ember-router-scroll's implementation of "pushState", then you can subclass and override a new location object from: import HistoryLocation from '@ember/routing/history-location'; [deprecation id: ember-router-scroll]`
https://github.com/DockYard/ember-router-scroll/blob/695d89485927f6637a9c2631904b67bbc3f3087a/addon/locations/router-scroll.js#L11-L41

**Pull request merged**
